import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import '@/styles/index.css'
import { Navbar } from '@/components/ui'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logoNew3.svg'
  }
}
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body>
          <Navbar />
          {children}
          <Toaster
          position='top-center'
            toastOptions={{
              // classNames: {
              //   toast: 'bg-[#2B3146]  border-[#F969AA] ',
              //   title: 'text-[#57A3E1]',
              //   description: 'text-red-400',
              //   actionButton: 'bg-zinc-400',
              //   cancelButton: 'bg-orange-400',
              //   closeButton: 'bg-lime-400'
              // }
              className:"p-toast-message-content"
            }}
          />
        </body>
      </PrimeReactProvider>
    </html>
  )
}
