import type { Metadata } from "next"
import { PrimeReactProvider } from "primereact/api"
import "@/styles/index.css"
import { Navbar } from "@/components/ui"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  )
}
