import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import '@/styles/index.css'
import { Navbar } from '@/components/ui'
import { Toaster } from 'sonner'
import 'primereact/resources/themes/lara-dark-purple/theme.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logoNew3.svg'
  }
}
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body>
          <Navbar />
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              className: 'p-toast-message-content'
            }}
          />
        </body>
      </PrimeReactProvider>
    </html>
  )
}
