export * from './dashboard/TablesWorkSpaces';
export * from './dashboard/WorkSpaces';
export * from './modals/dashboard/ModalDashboard';
export * from './modals/dashboard/ModalNewBoard';
export * from './modals/dashboard/tarjetas/ModalTareas';
export * from './modals/dashboard/tarjetas/ModalTarjetas';
export * from './modals/LoginModal';
export * from './modals/ModalRegister';
export * from './tablas/Tarjeta';
